### PR TITLE
Implement `config load /foo/filename.yml` and add pip for debian based distros

### PR DESCRIPTION
**Pull request by maltekrupa**
Hi,

I noticed `config load foobar.yml` just plain exits mesosctl and discovered that the code for this functionality was missing. I just copied a couple of lines and tested it locally.

The commit message screwed up because of backticks in the message, sorry.

Regards
Malte

### CODE REVIEW

**Comment by tobilg** [comment]
Thanks for the pull request! As I fixed the issues already in other commits/releases, I'll closed this one. But thanks for the hints and the testing!

**Comment by maltekrupa** [comment]
This feature is still missing on the master branch.
Currently if you do a `config load /filename.yml` nothing happens when you haven't already loaded a configuration. If you already have a configuration, then it works. -> https://github.com/mesoshq/mesosctl/pull/2/commits/069134e637b90da95d559da70e42507af9dc5246

Also, python-pip is missing on debian based distributions. -> https://github.com/mesoshq/mesosctl/pull/2/commits/ba77e62ed9db6bf024ce85c60c620048d7d8d112

**Comment by tobilg** [comment]
The pip install was added this morning on master: https://github.com/mesoshq/mesosctl/commit/ec9b24c1cb335e4c101c415195e66231db3fee41

The fix for `config load` is contained in https://github.com/mesoshq/mesosctl/commit/ec0002e64bef012bae646537143d7ee8fde197a1

Version `0.1.5` was published to NPM, and the Docker Hub is currently building the Docker image.

**Comment by maltekrupa** [comment]
Ah, cool. Thanks!

**Pull request closed without merging**
